# 액션 메타데이터
name: "Unified Lint Action"
description: "통합 린트 액션 (ESLint with Prettier, Stylelint, Markdownlint, Misspell)"
author: "Jonsoku"

# 버전 관리 주석 (수정하지 마세요!)
# ESLint 액션 버전: 2fee6dd72a5419ff4113f694e2068d2a03bb35dd
# Stylelint 액션 버전: dd2b435cc6a7c82705307a9dee740c9bbaa10411
# Markdownlint 액션 버전: 3667398db9118d7e78f7a63d10e26ce454ba5f58
# Misspell 액션 버전: 9daa94af4357dddb6fd3775de806bc0a8e98d3e4

inputs:
  workdir:
    description: "작업 디렉토리 경로"
    required: false
    default: "."

  github_token:
    description: "GitHub Token"
    required: true
    default: ${{ github.token }}

  reporter:
    description: "reviewdog 리포터 [github-pr-check,github-check,github-pr-review]"
    required: false
    default: "github-pr-review"

  filter_mode:
    description: "reviewdog 필터 모드 [added,diff_context,file,nofilter]"
    required: false
    default: "added"

  level:
    description: "리포트 레벨 [info,warning,error]"
    required: false
    default: "info"

  fail_level:
    description: "실패 레벨 [none,any,info,warning,error]"
    required: false
    default: "warning"

  # 린트 도구 활성화/비활성화
  skip_eslint:
    description: "ESLint (with Prettier) 스킵"
    required: false
    default: "false"

  skip_stylelint:
    description: "Stylelint 스킵"
    required: false
    default: "false"

  skip_markdownlint:
    description: "Markdownlint 스킵"
    required: false
    default: "false"

  skip_misspell:
    description: "Misspell 스킵"
    required: false
    default: "false"

  # ESLint 설정
  eslint_flags:
    description: "ESLint 검사 패턴 (Prettier 포함)"
    required: false
    default: "**/*.{js,jsx,ts,tsx}"

  eslint_config_path:
    description: "ESLint 설정 파일 경로"
    required: false
    default: ""

  # Stylelint 설정
  stylelint_input:
    description: "Stylelint 검사 패턴"
    required: false
    default: "**/*.css"

  stylelint_config_path:
    description: "Stylelint 설정 파일 경로"
    required: false
    default: ""

  # Markdownlint 설정
  markdownlint_flags:
    description: "Markdownlint 검사 패턴"
    required: false
    default: "**/*.md"

  markdownlint_config_path:
    description: "Markdownlint 설정 파일 경로"
    required: false
    default: ""

  # Misspell 설정
  misspell_locale:
    description: "Misspell 로케일 (US/UK)"
    required: false
    default: "US"

  misspell_ignore:
    description: "Misspell 무시할 단어 목록 (콤마로 구분)"
    required: false
    default: ""

  # 디버그 모드
  debug_mode:
    description: "디버그 모드 활성화"
    required: false
    default: "false"

  # 통지 설정
  notification_type:
    description: "통지 유형 [none,slack,email,both]"
    required: false
    default: "none"
  
  # Slack 설정
  slack_webhook_url:
    description: "Slack Webhook URL (Enterprise 버전: slack://your-enterprise-url)"
    required: false
  
  slack_channel:
    description: "Slack 채널명 (#으로 시작)"
    required: false
  
  slack_username:
    description: "Slack 봇 사용자명"
    required: false
    default: "Lint Action Bot"
    
  slack_icon_emoji:
    description: "Slack 봇 아이콘 이모지"
    required: false
    default: ":lint:"
  
  # 이메일 설정
  email_server_type:
    description: "이메일 서버 유형 [smtp,enterprise]"
    required: false
    default: "smtp"
    
  email_host:
    description: "SMTP 서버 호스트 또는 Enterprise 메일 API 엔드포인트"
    required: false
  
  email_port:
    description: "SMTP 서버 포트"
    required: false
    default: "587"
    
  email_username:
    description: "이메일 계정 사용자명"
    required: false
  
  email_password:
    description: "이메일 계정 비밀번호 또는 API 키"
    required: false
  
  email_from:
    description: "발신자 이메일 주소"
    required: false
  
  email_to:
    description: "수신자 이메일 주소 (콤마로 구분)"
    required: false

runs:
  using: "composite"
  steps:
    # 1. 환경 설정
    - name: Setup environment
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        echo "REVIEWDOG_GITHUB_API_TOKEN=${{ inputs.github_token }}" >> $GITHUB_ENV
        if [ "${{ inputs.debug_mode }}" == "true" ]; then
          echo "Debug mode enabled"
          set -x
        fi

    # 2. reviewdog 설치
    - name: Setup reviewdog
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest

    # 3. Node.js 설정
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 4. 작업 공간 설정 및 패키지 설치
    - name: Setup workspace
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        node ${{ github.action_path }}/setup-workspace.js

    # 5. 설정 파일 생성
    - name: Setup configurations
      shell: bash
      working-directory: ${{ inputs.workdir }}
      run: |
        node ${{ github.action_path }}/setup-configs.js

    # 6. ESLint (with Prettier) 실행
    - name: Run ESLint with Prettier
      if: inputs.skip_eslint != 'true'
      id: eslint
      uses: reviewdog/action-eslint@2fee6dd72a5419ff4113f694e2068d2a03bb35dd
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ inputs.reporter }}
        filter_mode: ${{ inputs.filter_mode }}
        level: error
        fail_level: ${{ inputs.fail_level }}
        eslint_flags: '${{ inputs.eslint_flags }} -f json -o eslint_report.json'
        workdir: ${{ inputs.workdir }}
      continue-on-error: true

    - name: Count ESLint Results
      if: inputs.skip_eslint != 'true'
      id: eslint_count
      shell: bash
      run: |
        if [ -f "eslint_report.json" ]; then
          errors=$(cat eslint_report.json | jq '[.[] | select(.severity == 2)] | length')
          warnings=$(cat eslint_report.json | jq '[.[] | select(.severity == 1)] | length')
        else
          errors=0
          warnings=0
        fi
        echo "error_count=$errors" >> $GITHUB_OUTPUT
        echo "warning_count=$warnings" >> $GITHUB_OUTPUT

    # 7. Stylelint 실행
    - name: Run Stylelint
      if: inputs.skip_stylelint != 'true'
      id: stylelint
      uses: reviewdog/action-stylelint@dd2b435cc6a7c82705307a9dee740c9bbaa10411
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ inputs.reporter }}
        filter_mode: ${{ inputs.filter_mode }}
        level: error
        fail_level: ${{ inputs.fail_level }}
        stylelint_input: ${{ inputs.stylelint_input }}
        stylelint_flags: '--custom-formatter=node_modules/stylelint-formatter-pretty'
        packages: 'stylelint-config-standard stylelint-formatter-pretty'
        workdir: ${{ inputs.workdir }}
      continue-on-error: true

    - name: Count Stylelint Results
      if: inputs.skip_stylelint != 'true'
      id: stylelint_count
      shell: bash
      run: |
        if [ -f "stylelint_report.txt" ]; then
          errors=$(grep -c "✖" stylelint_report.txt || echo "0")
          warnings=$(grep -c "⚠" stylelint_report.txt || echo "0")
        else
          errors=0
          warnings=0
        fi
        echo "error_count=$errors" >> $GITHUB_OUTPUT
        echo "warning_count=$warnings" >> $GITHUB_OUTPUT

    # 8. Markdownlint 실행
    - name: Run Markdownlint
      if: inputs.skip_markdownlint != 'true'
      id: markdownlint
      uses: reviewdog/action-markdownlint@3667398db9118d7e78f7a63d10e26ce454ba5f58
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ inputs.reporter }}
        filter_mode: ${{ inputs.filter_mode }}
        level: error
        fail_level: ${{ inputs.fail_level }}
        markdownlint_flags: '${{ inputs.markdownlint_flags }} --json > markdownlint_report.json'
      continue-on-error: true

    - name: Count Markdownlint Results
      if: inputs.skip_markdownlint != 'true'
      id: markdownlint_count
      shell: bash
      run: |
        if [ -f "markdownlint_report.json" ]; then
          errors=$(cat markdownlint_report.json | jq 'length')
        else
          errors=0
        fi
        echo "error_count=$errors" >> $GITHUB_OUTPUT

    # 9. Misspell 실행
    - name: Run Misspell
      if: inputs.skip_misspell != 'true'
      id: misspell
      uses: reviewdog/action-misspell@9daa94af4357dddb6fd3775de806bc0a8e98d3e4
      with:
        github_token: ${{ inputs.github_token }}
        reporter: ${{ inputs.reporter }}
        filter_mode: ${{ inputs.filter_mode }}
        level: error
        fail_level: ${{ inputs.fail_level }}
        locale: ${{ inputs.misspell_locale }}
        ignore: ${{ inputs.misspell_ignore }}
        pattern: "**/*"
        path: ${{ inputs.workdir }}
        output: "misspell_report.txt"
      continue-on-error: true

    - name: Count Misspell Results
      if: inputs.skip_misspell != 'true'
      id: misspell_count
      shell: bash
      run: |
        if [ -f "misspell_report.txt" ]; then
          errors=$(wc -l < misspell_report.txt || echo "0")
        else
          errors=0
        fi
        echo "error_count=$errors" >> $GITHUB_OUTPUT

    # 10. 결과 수집
    - name: Collect Results
      shell: bash
      run: |
        # 각 린터의 결과 수집
        if [ "${{ inputs.skip_eslint }}" != "true" ]; then
          eslint_errors="${{ steps.eslint_count.outputs.error_count }}"
          eslint_warnings="${{ steps.eslint_count.outputs.warning_count }}"
        else
          eslint_errors=0
          eslint_warnings=0
        fi

        if [ "${{ inputs.skip_stylelint }}" != "true" ]; then
          stylelint_errors="${{ steps.stylelint_count.outputs.error_count }}"
          stylelint_warnings="${{ steps.stylelint_count.outputs.warning_count }}"
        else
          stylelint_errors=0
          stylelint_warnings=0
        fi

        if [ "${{ inputs.skip_markdownlint }}" != "true" ]; then
          markdownlint_errors="${{ steps.markdownlint_count.outputs.error_count }}"
        else
          markdownlint_errors=0
        fi

        if [ "${{ inputs.skip_misspell }}" != "true" ]; then
          misspell_errors="${{ steps.misspell_count.outputs.error_count }}"
        else
          misspell_errors=0
        fi

        # 결과를 환경 변수로 저장
        {
          echo "LINT_RESULTS<<EOF"
          echo "린트 결과 요약:"
          echo "----------------------------------------"
          echo "ESLint: ${eslint_errors:-0} errors, ${eslint_warnings:-0} warnings"
          echo "Stylelint: ${stylelint_errors:-0} errors, ${stylelint_warnings:-0} warnings"
          echo "Markdownlint: ${markdownlint_errors:-0} errors"
          echo "Misspell: ${misspell_errors:-0} errors"
          echo "----------------------------------------"
          echo "총 에러 수: $((${eslint_errors:-0} + ${stylelint_errors:-0} + ${markdownlint_errors:-0} + ${misspell_errors:-0}))"
          echo "EOF"
        } >> $GITHUB_ENV

        # 전체 에러 수 계산 (null 값을 0으로 처리)
        total_errors=$((${eslint_errors:-0} + ${stylelint_errors:-0} + ${markdownlint_errors:-0} + ${misspell_errors:-0}))
        echo "TOTAL_ERRORS=$total_errors" >> $GITHUB_ENV

    # 11. Slack 통지
    - name: Send Slack Notification
      if: inputs.notification_type == 'slack' || inputs.notification_type == 'both'
      shell: bash
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack_webhook_url }}
        SLACK_CHANNEL: ${{ inputs.slack_channel }}
        SLACK_USERNAME: ${{ inputs.slack_username }}
        SLACK_ICON_EMOJI: ${{ inputs.slack_icon_emoji }}
        LINT_RESULTS: ${{ env.LINT_RESULTS }}
      run: |
        node ${{ github.action_path }}/notify/slack.js

    # 12. 이메일 통지
    - name: Send Email Notification
      if: inputs.notification_type == 'email' || inputs.notification_type == 'both'
      shell: bash
      env:
        EMAIL_SERVER_TYPE: ${{ inputs.email_server_type }}
        EMAIL_HOST: ${{ inputs.email_host }}
        EMAIL_PORT: ${{ inputs.email_port }}
        EMAIL_USERNAME: ${{ inputs.email_username }}
        EMAIL_PASSWORD: ${{ inputs.email_password }}
        EMAIL_FROM: ${{ inputs.email_from }}
        EMAIL_TO: ${{ inputs.email_to }}
        LINT_RESULTS: ${{ env.LINT_RESULTS }}
      run: |
        node ${{ github.action_path }}/notify/email.js
