name: Update Dependencies
on:
  schedule:
    - cron: '0 0 * * *'  # 매일 UTC 00:00에 실행
  workflow_dispatch:  # 수동 실행 가능

jobs:
  update-deps:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # PR 생성을 위한 권한
      pull-requests: write  # PR 생성을 위한 권한
    strategy:
      matrix:
        dep:
          - name: eslint
            repo: reviewdog/action-eslint
            current_sha: 2fee6dd72a5419ff4113f694e2068d2a03bb35dd
          - name: stylelint
            repo: reviewdog/action-stylelint
            current_sha: dd2b435cc6a7c82705307a9dee740c9bbaa10411
          - name: markdownlint
            repo: reviewdog/action-markdownlint
            current_sha: 3667398db9118d7e78f7a63d10e26ce454ba5f58
          - name: misspell
            repo: reviewdog/action-misspell
            current_sha: 9daa94af4357dddb6fd3775de806bc0a8e98d3e4

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Check for updates
        id: check
        run: |
          LATEST_SHA=$(curl -s "https://api.github.com/repos/${{ matrix.dep.repo }}/commits/master" | jq -r .sha)
          echo "latest_sha=${LATEST_SHA}" >> $GITHUB_OUTPUT
          if [ "$LATEST_SHA" != "${{ matrix.dep.current_sha }}" ]; then
            echo "update_needed=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.check.outputs.update_needed == 'true'
        uses: peter-evans/create-pull-request@c5a7806660adbe173f04e3e038b0ccdcd758773c # v6.1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore(deps): update ${{ matrix.dep.name }} to ${{ steps.check.outputs.latest_sha }}"
          title: "chore(deps): update ${{ matrix.dep.name }} action"
          body: |
            Update ${{ matrix.dep.name }} action to latest version
            - Previous version: ${{ matrix.dep.current_sha }}
            - New version: ${{ steps.check.outputs.latest_sha }}
            
            Auto-generated by [depup workflow](https://github.com/${{ github.repository }}/actions?query=workflow%3A"Update+Dependencies")
          branch: "deps/${{ matrix.dep.name }}-update"
          base: main
          labels: "dependencies,automated-pr" 