name: Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    types:
      - labeled

jobs:
  release:
    if: github.event.action != 'labeled'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Bump version
        if: "!startsWith(github.ref, 'refs/tags/')"
        id: bumpr
        uses: haya14busa/action-bumpr@78ab5a104d20896c9c9122c64221b3aecf1a8cbb # v1.10.0
        with:
          default_bump_level: patch
          tag_name: v%s

      - name: Update Semver
        if: ${{ steps.bumpr.outputs.skip != 'true' }}
        uses: haya14busa/action-update-semver@fb48464b2438ae82cc78237be61afb4f461265a1 # v1.2.1
        with:
          tag: ${{ steps.bumpr.outputs.next_version }}
          
      - name: Get Tag
        id: tag
        uses: haya14busa/action-cond@94f77f7a80cd666cb3155084e428254fea4281fd # v1.2.1
        with:
          cond: ${{ startsWith(github.ref, 'refs/tags/') }}
          if_true: ${{ github.ref }}
          if_false: ${{ steps.bumpr.outputs.next_version }}

      - name: Create Release
        if: ${{ steps.tag.outputs.value != '' }}
        env:
          TAG_NAME: ${{ steps.tag.outputs.value }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "${TAG_NAME}" \
            --title "Release ${TAG_NAME/refs\/tags\//}" \
            --generate-notes

  release-check:
    if: github.event.action == 'labeled'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Post bumpr status comment
        uses: haya14busa/action-bumpr@78ab5a104d20896c9c9122c64221b3aecf1a8cbb # v1.10.0 